app_id: '1626789534278136'
app_secret: 783ed795b5ec56bdcc5d33acb1ea8da1
api_version: v2.3
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles:
  administrator: '0'
  nun_staff: '0'
  blogger: '0'
  super_user: '0'
  ee_class: '0'
_core:
  default_config_hash: JJ2pkb09VwVm5U7EFJhYMC3keuZN0Le2_YRvZwZbzeQ

