status: '1'
pattern: '[node:field_date_of_observation:date:custom:Y]/[node:field_date_of_observation:date:custom:m]/[node:field_date_of_observation:date:custom:d] Observation for [node:field_tree_specimen:entity:title]'
php: 0
escape: 0
dependencies:
  config:
    - node.type.tree_data
