app_id: ''
app_secret: ''
api_version: v2.10
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles: {  }
_core:
  default_config_hash: WndXFDY9CEEG_AqDRG0TFa79Q6hhtkyRw4Ec108U5KM
